### ISSUE TITLE
Password _+1

### ISSUE THREAD

**Issue by luizaugustopc** [x0b/rcx#100]
#### Pre-Submission checklist

 - [ ] There is no existing issue that already asks for this feature.<br />
       _If no, please add a_ +1, _and maybe a comment if you have more to add._
 - [ ] The feature already exists in rclone (on your PC or in Termux)
 - [ ] I am prepared to help make this feature

#### What version of RCX are you using (About -> App version)? 
1.11.4

#### What problem are you trying to solve?
Add entering rclone.conf password everytime starts RCX. It is more secure.

**Comment by x0b** [comment]
Thank you for your contribution. You can voice your support in #12, where we are already tracking this idea.
