### ISSUE TITLE
Cleaning up the download notification

### ISSUE THREAD

**Issue by yoichi924** [x0b/rcx#102]
#### Pre-Submission checklist

 - [x] There is no existing issue that already asks for this feature.<br />
       _If no, please add a_ +1, _and maybe a comment if you have more to add._
 - [ ] The feature already exists in rclone (on your PC or in Termux)
 - [ ] I am prepared to help make this feature

#### What version of RCX are you using (About -> App version)?

1.11.4

#### What problem are you trying to solve?

The notification when downloading a file looks bad

#### What should RCX be able to do differently with help this problem?

I'm running Android 10 on a Honor 7X. I have setup a Google Drive remote.
[This is what the notification when starting up a download looks like](https://pasteboard.co/JCvjrF5o.jpg)
[This is what it looks like when the download has started](https://pasteboard.co/JCvk5b2.jpg)

My request is to change the notification when downloading a file to make it cleaner and provide more information in a meaningful way. 

The header with the name of the file being downloaded is of course very important. The first line with the file size and progress (in size and percentage) along with speed and ETA is also very helpful.

But the next line where the name of the file is repeated is basically useless and not required. Then the progress (only in percentage), speed and ETA again (with sometimes conflicting information) is confusing and also not required. Then the 2 nulls for some reason. And finally a transferred 0/1,0% . 

Now this might make sense if you're downloading 2 or more files at once but since it download the files one after the other (atleast in my experience) anyway and not in parallel, dosent really make sense.

My suggestion is this:
Header and first line stay the same. Remove the repeated name, the conflicting information, the nulls and the transferred thing.

I understand this may be because of how it is setup. As in its meant to be a all-in-one notification for downloading from different services with different information. But if you could it a bit more cleaner with more usef information, would be really appreciated. Thank you.

**Comment by x0b** [comment]
RCX dumps the internal progess message from rclone into a notification (see also [rcloneExplorer#154](https://github.com/kaczmarkiewiczp/rcloneExplorer/issues/154#issuecomment-410626409)). We do have some capacity to change that though.

The log-term plan is to actually make this notification show statistics for all transfers, but at the moment it only refers to the last download.

> My suggestion is this:
> Header and first line stay the same. Remove the repeated name, the conflicting information, the nulls and the transferred thing.

Here's what we can do:
 - [ ] Remove nulls
 - [ ] Remove `Transferred` if only one file is transferred
 - [ ] Remove per-file information in case only a single file is transferred

**Comment by b3njibr0** [comment]
Yeah, that makes sense.

Can I ask, does rclone download multiple files in parallel or one after the other?

I would also like to change my suggestion for the repeated file. 
* If it's only one file, only have the header as the name of the file and remove the repeated one. 
* If it's multiple files, the header could be "Downloading [Number of files]" and then each file's name can be shown as they are downloaded.

Also, why does transferred have to be `0 / 1,0%` ? Why the comma and why the percentage? 

I assume the second line with progress, speed and ETA is the info for all current downloads and then the corresponding info for each file is shown under its own header. That makes sense I guess, but it's too much information in a small notification in my opinion. I would suggest only have the info for all files. Add a downloading section in the app which shows what's downloading and it's individual info. If that's possible.
