### ISSUE TITLE
Update README to clarify that file data is encrypted using XSalsa20, not AES

### ISSUE THREAD

**Issue by TJ-Hooker15** [x0b/rcx#103]
#### Pre-Submission checklist

 - [X] There is no existing issue that already asks for this feature.<br />
       _If no, please add a_ +1, _and maybe a comment if you have more to add._
 - [ ] The feature already exists in rclone (on your PC or in Termux)
 - [ ] I am prepared to help make this feature

#### What version of RCX are you using (About -> App version)?
Release 1.11.4

#### What problem are you trying to solve?
The current documentation is technically inaccurate.

According to Rclone's documentation, it uses XSalsa20 to encrypt data. AES256 is only used for file name encryption. RCX readme states "256 Bit AES Encryption: Keep your files private on any cloud provider with crypt remotes." In my opinion this implies that the file data is encrypted with AES256, which is not the case.

https://rclone.org/crypt/

#### What should RCX be able to do differently with help this problem?
RCX documentation should be updated to clarify that 256 bit XSalsa20 is used to encrypt data. Or possibly just state 256 bit encryption is used (without explicitly mentioning the cipher), and include a reference to Rclone crypt documentation for more details on encryption.

**Comment by x0b** [comment]
Good find! Do you want to submit a pull request? [You can edit the file directly on GitHub.](https://github.com/x0b/rcx/edit/master/README.md)

Since there isn't really space to discuss encryption details, I'd remove the 'AES' and maybe place a link to the rclone documentation, e.g.:

```diff
- Cloud Access | 256 Bit AES Encryption | Integrated Experience
+ Cloud Access | 256 Bit Encryption<sup>[1](https://rclone.org/crypt/#file-encryption)</sup> | Integrated Experience
```
