### ISSUE TITLE
Support "exFAT/NTFS for USB" as DocumentsProvider

### ISSUE THREAD

**Issue by Ali-Al1** [x0b/rcx#105]
Hi,

I received this message "Third party not yet supported. Open an issue with the affected app name." when trying to add storage mounted with this app:

https://play.google.com/store/apps/details?id=com.paragon.tcplugins_ntfs_ro

![Screenshot_20201216-203401](https://user-images.githubusercontent.com/11404482/102403476-3803e100-3fde-11eb-9799-e6b705b40e20.png)

rclone: v1.51.0
rcloneExplorer: 1.11.4
android-sdk: 28
android-device: NX629J
android-ndk-abis: arm64-v8a;armeabi-v7a;armeabi

**Comment by x0b** [comment]
Thank you for reporting this.

The feature you are trying to use currently only supports storage spaces provided by Android itself (Internal Storage, SD Cards, USB drives, etc.). RCX uses system interfaces (SAF specifically) in a not standards-compliant way to achieve acceptable performance. 

We will provide a compatible version in a upcoming release.

**Comment by x0b** [comment]
Fixed in f8dc1396ee5b112d434565e0cd5bbc881fc3dcf2.

**Comment by x0b** [comment]
Closing as `v1.12.0` has been released.
