### ISSUE TITLE
Union not working on Cloud Storage Remotes

### ISSUE THREAD

**Issue by curious-porcupine** [x0b/rcx#108]
Hi,

Ive been trying to use the Union to merge two cloud storage remotes I've already created in the app. The merge seems to be going fine but when I try to access the merged folder the app throws an error stating 'Error Retrieving directory content'. Im also attaching the config file where you can see the entry for the Union between pcloud and drive.

> 2021-01-03 22:31:37 - 2021/01/04 03:31:37 DEBUG : rclone: Version "v1.51.0" starting with parameters ["/data/app/io.github.x0b.rcx-9ATM-i4YQNNCof80_O__2g==/lib/arm64/librclone.so" "--cache-chunk-path" "/data/user/0/io.github.x0b.rcx/cache" "--cache-db-path" "/data/user/0/io.github.x0b.rcx/cache" "--config" "/data/user/0/io.github.x0b.rcx/files/rclone.conf" "-vvv" "lsjson" "Combined:"]
2021/01/04 03:31:37 DEBUG : Using config file from "/data/user/0/io.github.x0b.rcx/files/rclone.conf"
2021/01/04 03:31:37 Failed to create file system for "Combined:": didn't find section in config file

Config file export :

> [5d44cd8d-397c-4107-b79b-17f2b6a071e8]
type = alias
remote = /storage/emulated/0 
[GDrive Pro]
type = drive
scope = drive
token = "Redacted for privacy"

> [Pcloud]
type = pcloud
token = "Redacted for privacy"

> [Combined]
type = union
remotes = Pcloud:Rclone Encrypted GDrive Pro:RcloneEncrypted

**Comment by x0b** [comment]
Could be a bug in rclone itself. We'll need to re-verify this on RCX 1.12 (Rclone 1.54).

**Comment by x0b** [comment]
Version `v1.12.0` has released with rclone `1.55.1`. Please update and test again. If you still have this issue, please [open a new thread in the rclone forum](forum.rclone.org/) or a new issue in the rclone repo.
