### ISSUE TITLE
The app doesn'tsupport a cloud of mail.ru

### ISSUE THREAD

**Issue by akerka2** [x0b/rcx#109]
RCX does'n support cloud.mail.ru, although rclone itself supports it very fine (https://rclone.org/mailru/)
If I push + button (add new remote) I see a list with all clouds except mail.ru.

rclone: v1.51.0
rcloneExplorer: 1.11.4: 28
android-device: Redmi Note 8
android-ndk-abis: arm64-v8a;armeabi-v7a;armeabi
```

**Comment by x0b** [comment]
Thank you for your suggestion. Please voice your support on the already open issue #60.
