### ISSUE TITLE
Moving Files Between Different Shared Or Team Drives

### ISSUE THREAD

**Issue by iamLiquidX** [x0b/rcx#111]
#### Pre-Submission checklist

 - [x] There is no existing issue that already asks for this feature.<br />
       _If no, please add a_ +1, _and maybe a comment if you have more to add._
 - [x] The feature already exists in rclone (on your PC or in Termux)
 - [x] I am prepared to help make this feature

#### What version of RCX are you using (About -> App version)?
1.11.4

#### What problem are you trying to solve?
Moving Data Between Different Shared Drives

#### What should RCX be able to do differently with help this problem?

It would be great addition if we can move data between  two different shared drives, right now it only allows to move data inside only one shared drive.

**Comment by x0b** [comment]
See #49.
