### ISSUE TITLE
Add a copy action/operation

### ISSUE THREAD

**Issue by 1024mb** [x0b/rcx#117]
#### Pre-Submission checklist

 - [x] There is no existing issue that already asks for this feature.<br />
       _If no, please add a_ +1, _and maybe a comment if you have more to add._
 - [x] The feature already exists in rclone (on your PC or in Termux)
 - [x] I am prepared to help make this feature

#### What version of RCX are you using (About -> App version)?

1.11.4

#### What problem are you trying to solve?

Currently there is only a Sync option which if the name is correct it means that whenever you delete a file on one end it should propagate, it would be great if we could have a Copy option so we can just upload our data and be able to delete it without it being also deleted on the remote.

#### What should RCX be able to do differently with help this problem?

Have a Copy option.

**Comment by x0b** [comment]
Copying between remotes and local already works and is named download or upload, depending on the direction. Copying between non-local remotes requires #49.

**Comment by 1024mb** [comment]
Thanks for the information, I don't know how I didn't think of that.
