### ISSUE TITLE
FTP config wizard: support for advanced parameters (encoding type, connect mode)

### ISSUE THREAD

**Issue by xuanix** [x0b/rcx#122]

**Comment by x0b** [comment]
Thank you for your feature request. By the way, you can import an existing rclone configuration file (`rclone.conf`) with all available advanced options ([RCX documentation](https://x0b.github.io/docs/)).

Could you explain what you mean by connect mode? Rclone does not have that as a parameter.

**Comment by x0b** [comment]
Closing without answer from issue creator.
