### ISSUE TITLE
delete is slow on folders with many files

### ISSUE THREAD

**Issue by adjenks** [x0b/rcx#124]
#### Pre-Submission checklist

 - [x] There is no existing issue that already asks for this feature.<br />
       _If no, please add a_ +1, _and maybe a comment if you have more to add._
 - [ ] The feature already exists in rclone (on your PC or in Termux)
 - [ ] I am prepared to help make this feature

#### What version of RCX are you using (About -> App version)?

1.11.4

#### What problem are you trying to solve?

I'm experiencing the same issue as discussed here:

https://forum.rclone.org/t/rclone-delete-with-large-remote-folders/14701

You seem to be able to solve it by changing the commands used.

Currently it takes me more than one minute to delete each file in a folder with hundreds of thousands of files. It will take hundreds of thousands of minutes to complete. I'm guessing it will gradually get faster and faster because the list of files will get shorter. It's slow because the basic delete command returns an updated list of files.

#### What should RCX be able to do differently with help this problem?

Use `rclone deletefile` or `rclone delete --files-from` to speed up deletion in large folders.

**Comment by x0b** [comment]
**1)** Could you please fill in the complete template?

**2)** I've read through the linked forum post, and it is not entirely clear to me
&nbsp;&nbsp;&nbsp;&nbsp;a) What is the slow command?
&nbsp;&nbsp;&nbsp;&nbsp;b) Which commands and/or flags are faster?

**3)** How are you deleting your files? Do you delete folders, single files, selections of multiple files or something else entirely?

**Comment by adjenks** [comment]
Sorry, the template did not appear on my cellphone but I can see it here on my computer now...

**Comment by x0b** [comment]
Okay, from reading your comments and the rclone docs, we could do the following things:
 * Use `rclone deletefile <file-path>` for single files
 * Use `rclone delete <parent-path> --include={file1, file2, file}`

How long does `rclone deletefile <filepath>` take on your 50'000 folder? It seems like this should be a useful optimization.

**Comment by adjenks** [comment]
Sorry I've been busy. I'll try to run some performance tests in the next few weeks and get back to you.

**Comment by x0b** [comment]
I've had a look at rclone itself - if my reading of the source code is correct, deletefile does indeed skip listing the parent folder/container ([delete](https://github.com/rclone/rclone/blob/master/fs/operations/operations.go#L1091-L1107) vs [deletefile](https://github.com/rclone/rclone/blob/6366d3dfc5232a3fa02666051135116bfe44653b/fs/operations/operations.go#L660-L697)). 

I've done some testing with really large folders and changed RCX to use `deletefile`. There is still some potential to make it even faster by deleting multiple files with a single rclone process, but lets keep this simple for now.

**Comment by xxxliqu1dxxx** [comment]
hi @x0b was this implemented in rclone? I have the same issue with rclone? Thanks.

**Comment by adjenks** [comment]
@xxxliqu1dxxx You should ask questions about rclone in the rclone repo. If you read the discussion above you can see that it is possible to speed up deletion if you use the right methods and parameters.
