### ISSUE TITLE
Bug: SFTP handshare failure when using key_pem

### ISSUE THREAD

**Issue by x0b** [x0b/rcx#134]
#### What version of RCX are you using (About -> App version)?
v1.12.0 pre

#### What is your Android version, phone model and manufacturer?
n/a

#### Config 
```
type = sftp
host = (..hidden..)
port = (..hidden..)
key_pem = -----BEGIN RSA PRIVATE KEY-----\n (...hidden...) \n-----END RSA PRIVATE KEY-----\n
md5sum_command = md5sum
sha1sum_command = sha1sum
```

#### What are the contents of ```Android/data/io.github.x0b.rcx/files/logs/log.txt```?
<details><summary><code>log.txt</code> (click to expand) </summary><br><pre>
2021-04-27 16:34:41 - 2021/04/27 20:34:29 DEBUG : Using config file from "/data/user/0/io.github.x0b.rcx/files/rclone.conf"
2021/04/27 20:34:29 DEBUG : rclone: Version "v1.55.0-rcx" starting with parameters ["/data/app/~~ryz6SorzuNDBlFZTl7tZ3g==/io.github.x0b.rcx-k7K-cUjfY9Z_R7KMMvkzzw==/lib/arm64/librclone.so" "--cache-chunk-path" "/data/user/0/io.github.x0b.rcx/cache" "--cache-db-path" "/data/user/0/io.github.x0b.rcx/cache" "--config" "/data/user/0/io.github.x0b.rcx/files/rclone.conf" "-vvv" "lsjson" "chi1:"]
2021/04/27 20:34:29 DEBUG : Creating backend with remote "sftp_remote:"
2021/04/27 20:34:30 DEBUG : pacer: low level retry 1/10 (error couldn't connect SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain)
2021/04/27 20:34:30 DEBUG : pacer: Rate limited, increasing sleep to 200ms
2021/04/27 20:34:30 DEBUG : pacer: low level retry 2/10 (error couldn't connect SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain)
2021/04/27 20:34:30 DEBUG : pacer: Rate limited, increasing sleep to 400ms
2021/04/27 20:34:30 DEBUG : pacer: low level retry 3/10 (error couldn't connect SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain)
2021/04/27 20:34:30 DEBUG : pacer: Rate limited, increasing sleep to 800ms
2021/04/27 20:34:30 DEBUG : pacer: low level retry 4/10 (error couldn't connect SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain)
2021/04/27 20:34:30 DEBUG : pacer: Rate limited, increasing sleep to 1.6s
2021/04/27 20:34:31 DEBUG : pacer: low level retry 5/10 (error couldn't connect SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain)
2021/04/27 20:34:31 DEBUG : pacer: Rate limited, increasing sleep to 2s
2021/04/27 20:34:33 DEBUG : pacer: low level retry 6/10 (error couldn't connect SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain)
2021/04/27 20:34:35 DEBUG : pacer: low level retry 7/10 (error couldn't connect SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain)
2021/04/27 20:34:37 DEBUG : pacer: low level retry 8/10 (error couldn't connect SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain)
2021/04/27 20:34:39 DEBUG : pacer: low level retry 9/10 (error couldn't connect SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain)
2021/04/27 20:34:41 DEBUG : pacer: low level retry 10/10 (error couldn't connect SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain)
2021/04/27 20:34:41 Failed to create file system for "sftp_remote:": NewFs: couldn't connect SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
</pre></details>

**Comment by x0b** [comment]
@bcliang Wait a second - your config is missing a user name. Please add the username and test again.

**Comment by bcliang** [comment]
For some reason, I thought `user` was optional with `key_pem`. Adding that worked. Apologies; please close the issue.

**Comment by x0b** [comment]
It is of optional, but only if your current user is also the remote user.
