### ISSUE TITLE
Unable to sync with nextcloud (The Good Host provider)

### ISSUE THREAD

**Issue by Kreyren** [x0b/rcx#135]
#### What version of RCX are you using (About -> App version)?

1.11.4, Rclone v1.51.0

#### What is your Android version, phone model and manufacturer?

LineageOS 17.1 using Android 10 (QQ3A.200805.001), ONE A3008 (OnePlus 2), OnePlus

#### Which steps are required to reproduce this issue?

0. Get free account from https://thegood.cloud/en/individuals and verify your e-mail
1. Create the new remote with following:
Type: WebDAV
Remote name: The Good Host
url of the http host to connect to: (either of)
- use02.thegood.cloud
- https://use02.thegood.cloud
- https://use02.thegood.cloud/remote.php/dav/files/kreyren@fsfe.org/
User name: <YOUR_USERNAME> e.g. kreyren@fsfe.org
Password: <YOUR_PASSWORD> e.g. `6GAj#%zn9~hCuemAcfsx`VshAvcZ#8LCf~rTNg~5PYd@9PfeGSop8FkUDPLismbkfEw9JK2JHa#zvdYFL8%ZbQg@TYax`~%WVjAcv8#GLF`x8wRWfk`%dcvZsQ7j2wGK` (generated from KeepAssXC)
- Name of the webdav service: Nextcloud
2. Expect failure to auth

#### What are the contents of ```Android/data/io.github.x0b.rcx/files/logs/log.txt```?
<details><summary><code>log.txt</code> (click to expand) </summary><br><pre>

blank

</pre></details>

#### Additional informations
App installed from f-droid

**Comment by x0b** [comment]
This is probably already fixed in rclone. We're currently in the process of rolling out v1.12 of RCX. F-Droid always takes a few days to pick up updates, please re-test with 1.12 when it arrives.

**Comment by x0b** [comment]
FIY: The F-Droid update is finally through, though we have just released the next version.

**Comment by x0b** [comment]
That is unfortunate. Since this is an issue with rclone, can you create a new bug topic in the [rclone forum](https://forum.rclone.org/c/bug/7)? The people over there know much more about rclone than me. You can get a log file by enabling logging in `Settings` > `Logging` > `Log Rclone errors`. If you need help with that, you can also tag me in the forum @x0b.

**Comment by x0b** [comment]
Closing as stale & the error probably only exists in rclone. If you still experience this issue on current versions, please test your configuration in Termux or on a desktop PC with rclone.
