### ISSUE TITLE
Unstable RCX serve

### ISSUE THREAD

**Issue by alscaldas** [x0b/rcx#137]
#### What version of RCX are you using (About -> App version)?
App version: 1.12.0 (the version available on the Play Store)
Rclone version: v1.55.1-rcx

#### What is your Android version, phone model and manufacturer?
Android 8, Samsung Galaxy S7 Edge

#### Which steps are required to reproduce this issue?

1. Open a crypt remote
2. Choose "serve" option (no matter which protocol chosen, although I've been trying to use mostly webdav).
3. After using it for a while (copying/moving files around, creating folders, etc) it just stops working. No apparently log messages. In this particular case I'm using Solid Explorer to browse the files. In fact I noticed that there was [another ticket](https://github.com/x0b/rcx/issues/25) already closed with an issue similar to mine but I thought it'd be better to open a new one anyway.

#### What is your configuration (`rclone.conf`)?
```
[GoogleDrive]
type = drive
client_id = ***
client_secret = ***
scope = drive
token = {"access_token":"***","token_type":"Bearer","refresh_token":"***","expiry":"2021-05-11T00:49:05.391805074Z"}

[GoogleDriveEnc]
type = crypt
remote = GoogleDrive:
password = ***
filename_encryption = Standard
directory_name_encryption = true

[5d44cd8d-397c-4107-b79b-17f2b6a071e8]
type = alias
remote = /storage/emulated/0
```

#### Does the same issue also occur when using the same configuration on a PC or in Termux?
I've never used Termux, but it works on my PC.

#### What are the contents of ```Android/data/io.github.x0b.rcx/files/logs/log.txt```?
<details><summary><code>log.txt</code> (click to expand) </summary><br><pre>

2021-05-11 06:35:28 - 2021/05/11 09:35:04 DEBUG : Using config file from "/data/user/0/io.github.x0b.rcx/files/rclone.conf"
2021/05/11 09:35:04 DEBUG : rclone: Version "v1.55.1-rcx" starting with parameters ["/data/app/io.github.x0b.rcx-d6da5-DbG_wT-P7txU3bXg==/lib/arm64/librclone.so" "--cache-chunk-path" "/data/user/0/io.github.x0b.rcx/cache" "--cache-db-path" "/data/user/0/io.github.x0b.rcx/cache" "--config" "/data/user/0/io.github.x0b.rcx/files/rclone.conf" "-vvv" "serve" "http" "--addr" "127.0.0.1:29179" "GoogleDriveEnc:" "--baseurl" "/0UehRTO-bHAbYeJHKdhesA/GoogleDriveEnc"]
2021/05/11 09:35:04 DEBUG : Creating backend with remote "GoogleDriveEnc:"
2021/05/11 09:35:04 DEBUG : Creating backend with remote "GoogleDrive:"
2021/05/11 09:35:05 DEBUG : Google drive root '': root_folder_id = "0AD8UBUc0_SjuUk9PVA" - save this in the config to speed up startup
2021/05/11 09:35:05 NOTICE: Encrypted drive 'GoogleDriveEnc:': Serving on http://127.0.0.1:29179/0UehRTO-bHAbYeJHKdhesA/GoogleDriveEnc/

2021-05-11 06:36:00 - 2021/05/11 09:35:59 DEBUG : Using config file from "/data/user/0/io.github.x0b.rcx/files/rclone.conf"
2021/05/11 09:35:59 DEBUG : rclone: Version "v1.55.1-rcx" starting with parameters ["/data/app/io.github.x0b.rcx-d6da5-DbG_wT-P7txU3bXg==/lib/arm64/librclone.so" "--cache-chunk-path" "/data/user/0/io.github.x0b.rcx/cache" "--cache-db-path" "/data/user/0/io.github.x0b.rcx/cache" "--config" "/data/user/0/io.github.x0b.rcx/files/rclone.conf" "-vvv" "serve" "http" "--addr" "127.0.0.1:29179" "GoogleDriveEnc:" "--baseurl" "/0UehRTO-bHAbYeJHKdhesA/GoogleDriveEnc"]
2021/05/11 09:35:59 DEBUG : Creating backend with remote "GoogleDriveEnc:"
2021/05/11 09:35:59 DEBUG : Creating backend with remote "GoogleDrive:"
2021/05/11 09:36:00 DEBUG : Google drive root '': root_folder_id = "0AD8UBUc0_SjuUk9PVA" - save this in the config to speed up startup
2021/05/11 09:36:00 NOTICE: Encrypted drive 'GoogleDriveEnc:': Serving on http://127.0.0.1:29179/0UehRTO-bHAbYeJHKdhesA/GoogleDriveEnc/

2021-05-11 07:20:58 - 2021/05/11 10:20:55 DEBUG : Using config file from "/data/user/0/io.github.x0b.rcx/files/rclone.conf"
2021/05/11 10:20:55 DEBUG : rclone: Version "v1.55.1-rcx" starting with parameters ["/data/app/io.github.x0b.rcx-d6da5-DbG_wT-P7txU3bXg==/lib/arm64/librclone.so" "--cache-chunk-path" "/data/user/0/io.github.x0b.rcx/cache" "--cache-db-path" "/data/user/0/io.github.x0b.rcx/cache" "--config" "/data/user/0/io.github.x0b.rcx/files/rclone.conf" "-vvv" "serve" "http" "--addr" "127.0.0.1:29179" "GoogleDriveEnc:" "--baseurl" "/T5joMwj8HwPV55arnx1aSg/GoogleDriveEnc"]
2021/05/11 10:20:55 DEBUG : Creating backend with remote "GoogleDriveEnc:"
2021/05/11 10:20:55 DEBUG : Creating backend with remote "GoogleDrive:"
2021/05/11 10:20:56 DEBUG : Google drive root '': root_folder_id = "0AD8UBUc0_SjuUk9PVA" - save this in the config to speed up startup
2021/05/11 10:20:56 NOTICE: Encrypted drive 'GoogleDriveEnc:': Serving on http://127.0.0.1:29179/T5joMwj8HwPV55arnx1aSg/GoogleDriveEnc/

</pre></details>

**Comment by x0b** [comment]
That's weird - serve basically a bookmark to [`rclone serve`](https://rclone.org/commands/rclone_serve/), and as such it should also happen on a PC. It is possible that rclone is somehow locking up. If I remember correctly, we need a backtrace and then @rclone/rclone can investigate.

RCX does not allow that though - can you try it in Termux? Here's what should work:
 1. Install Termux from GitHub or F-Droid, install rclone, run `termux-setup-storage` and export your config from RCX into the termux root directory.
 2. Start a rclone serve with logging in background: `rclone serve --log-file error.log serve webdav remotename &`
 3. Termux should then show something like `[1] 123456`
 4. Use the webdav serve until it gets stuck.
 5. Enter `kill -QUIT 123456` into Termux, replacing 123456 with the number that Termux showed you previously
 6. Armed with that error log, we can open an issue in rclone/rclone.

**Comment by alscaldas** [comment]
Sorry for the delay (as I wasn't used to termux had to read a little to learn some basics).

Anyway, I followed your instructions, the only difference being that as I got errors when tried to install the termux version from F-Droid I ended up installing it from Play Store. Not sure if it's relevant to the tests results...

I then run rclone serve using the rclone.conf exported from RCX and it's been working for a couple of hours without a single error (just to compare, when I run it from RCX I can only do a couple of operations on Solid Explorer - the file manager app I use - before it stop working). I tried all sorts of things, like copying and moving large and small files, opening my KeepassXC db file and making changes in it, letting my smartphone idle for some short periods of time with the webdav server running and it all happened without any errors or warnings being displayed on the error.log file.

By the way, here is the only line registered on the file:

```
2021/05/11 22:47:31 NOTICE: Encrypted drive 'GoogleDriveEnc:': WebDav Server started on http://127.0.0.1:8080/
```

I hope this may somehow help on your analysis and thanks again for taking the time to look into it.

**Comment by x0b** [comment]
Thank you for your efforts.

> Anyway, I followed your instructions, the only difference being that as I got errors when tried to install the termux version from F-Droid I ended up installing it from Play Store. Not sure if it's relevant to the tests results...

Which version of rclone did you test this on? I recommended F-Droid since the Play Store version of Termux is EOL, and may have installed an old version of rclone - which in turn may not contain the bug. 

The reason I'm asking is because I'm maintaining the Termux version of rclone as well, and they have the same build configuration.

**Comment by alscaldas** [comment]
```
$ rclone --version
rclone 1.55.1-termux
- os/type: android
- os/arch: arm64
- go/version: go1.16.3
- go/linking: dynamic
- go/tags:noselfupdate
```

**Comment by x0b** [comment]
I just released v1.12.1 with more debugging features to narrow this problem down. With those, you can generate a debug log.
To do this,
 1. Enable rclone error logging in the settings.
 2. Start a serve and get it stuck.
 3. Go back to the settings and press the new Debug: SIGQUIT button.
 4. Retrieve the log file from `Android/data/io.github.x0b.rcx/files/logs/serve.log`.

**Comment by alscaldas** [comment]
Hello,

Just to let you know that whatever you did which fixed [that issue](https://github.com/x0b/rcx/issues/129) (and at least to me it seems to be fixed as I've been using it for a couple of hours and it's working ook) apparently also fixed this one.

So this last release apparently fixed both issues I was having. I'd like once more to thank you for the excellent job you've been doing with this app.

**Comment by x0b** [comment]
That's good to hear, even if a little bit weird. Well, at least we now have more sophisticated in case such an issue pops up again.
