### ISSUE TITLE
Support full Rclone supported Storage Systems

### ISSUE THREAD

**Issue by Killerhaschen** [x0b/rcx#142]
#### Pre-Submission checklist

 - [x] There is no existing issue that already asks for this feature.<br />
 - [x] The feature already exists in rclone (on your PC or in Termux)
 - [x] I am prepared to help make this feature

#### What version of RCX are you using (About -> App version)?
Version 1.11.5
Rclone 1.51.0

#### What problem are you trying to solve?

Access files from FTPs share.
It would also be great if all storage systems supported by Rclone and all their options were supported here.

#### What should RCX be able to do differently to help with this problem?

Add the buttons and Settings to support alle the Storage backends with all Rclone options.

**Comment by Killerhaschen** [comment]
Is this just something that needs work to type and test or are there more problems?

**Comment by x0b** [comment]
[As described in our documentation](https://x0b.github.io/docs), RCX works with every rclone remote type, which are [documented on rclone.org](https://rclone.org/#providers).

> There are various types of remotes and rcx supports all storage remotes and most of the meta-remotes like crypt that encrypts other remotes and union that combines multiple remotes. You can see all supported remote types on rclone.org. **Note that you can only configure some types inside of the app, but you can always import a configuration to allow more remote types.**

You can configure basic FTP file shares in the app. If you need extended options (https://rclone.org/ftp/), you can import a pre-made configuration file into RCX. 

You can create extended configuration files with rclone on a PC or with Termux directly on your device.

**Comment by Killerhaschen** [comment]
Thank you. Then it was my mistake. I tried again and the second time it worked.
Maybe there was a problem because the conf that didn't work didn't have line breaks at the end.

**Comment by x0b** [comment]
Thats good to hear. I'm not sure about the line breaks, I will have to test that.

Closing as solved.
