### ISSUE TITLE
Vfs cache mode

### ISSUE THREAD

**Issue by victorbnl** [x0b/rcx#154]
#### Pre-Submission checklist

 - [x] There is no existing issue that already asks for this feature.<br />
 - [x] The feature already exists in rclone (on your PC or in Termux)
 - [ ] I am prepared to help make this feature

#### What version of RCX are you using (About -> App version)?

1.12.1

#### What problem are you trying to solve?

It's slow

#### What should RCX be able to do differently to help with this problem?

Something in the settings to select a mode

**Comment by x0b** [comment]
We have an issue (#121) to support VFS for `rclone serve`. Is there a different supported command where VFS works?

**Comment by victorbnl** [comment]
rclone mount, it's the only one I use so I don't know about others

**Comment by x0b** [comment]
Ah, unfortunately, I doubt that Google will ever allow mounting stuff (see #104). I'm going to close this since there is nothing we as app developers can really do. If there's anything new, we'll update the linked issues.
