### ISSUE TITLE
Allows users to set up regular synchronization of specified directories

### ISSUE THREAD

**Issue by Seele0oO** [x0b/rcx#231]
#### Pre-Submission checklist

 - [x] There is no existing issue that already asks for this feature.<br />
 - [ ] The feature already exists in rclone (on your PC or in Termux)
 - [ ] I am prepared to help make this feature

#### What version of RCX are you using (About -> App version)?
App version 1.12.2

#### What problem are you trying to solve?

This requirement stems from the fact that some software will only read local files and absolutely no other file systems.

#### What should RCX be able to do differently to help with this problem?

I would like to always synchronize one of my Onedrive folders with a local one, but currently Sync operations for fixed two directories are relatively cumbersome. On Rclone brownser you can configure a fixed list of tasks (this way is also good), if you can add a crontab-like function to this, it may be more convenient to synchronize files.
Or another way: create a mount point to the specified directory, but I don't know if Android allows this.

Anyway,Thanks for your contribution.

**Comment by Creekie1337** [comment]
I believe https://github.com/newhinton/extRact has this.
