### ISSUE TITLE
Update RClone

### ISSUE THREAD

**Issue by JulianICE08935** [x0b/rcx#246]
can you please update RClone in the App RCX

**Comment by mateo08c** [comment]
update app please ❤️

**Comment by arbaleast** [comment]
same request

**Comment by Elvis56NL** [comment]
Same, or maybe make a version that uses an external version of Rclone. The current version used lacks support for things like 

filename_encoding = base32768

**Comment by aluo-x** [comment]
https://github.com/newhinton/extRact Here is a maintained fork
