### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by dmotte** [x0b/rcx#53]
Hi! First of all, great work! Thank you very much for sharing this app. I think that this is very promising and has a great future.

It would be **awesome** if you could add this to [F-Droid](https://f-droid.org/) to deliver automatic updates to your users :wink:

**Comment by x0b** [comment]
You can join the [Alpha](https://forms.gle/5jLYhZwafx7nEfi16) (manual approval required, but always the newest features) or [Beta](https://play.google.com/apps/testing/io.github.x0b.rcx) (self-service) for automatic updates.

For F-Droid, see [#39](https://github.com/x0b/rcx/pull/39#issuecomment-601188586).

**Comment by x0b** [comment]
[We are finally available on F-Droid](https://f-droid.org/en/packages/io.github.x0b.rcx/) 🎉🥳.

It took quite a bit of work both from my and from the F-Droid side, but you can finally download RCX through F-Droid. We need to re-work some things slightly for v1.12, but after that every update should be merged automatically.

**Comment by dmotte** [comment]
Thank you!! :smile: how can i pay you a beer?

**Comment by alexanderadam** [comment]
@x0b this is _so_ wonderful! :+1: 

Maybe you want to add the F-Droid link also to [the website](https://x0b.github.io/) (and maybe to the GitHub readme, too?).

In any case: thank you _so_ much for your work!

**Comment by x0b** [comment]
@dmotte 
> Thank you!! 😄 how can i pay you a beer?

No need. I don't have have anything set up for that anyway 😂.

---

@alexanderadam 
Good idea, and thanks for the kind words.

**Comment by dmotte** [comment]
@x0b let me know if you set it up in the future. This app is extremely useful for me, so i think i owe you that beer anyways 😉
