### ISSUE TITLE
RCX 1.12 release plan announcement

### ISSUE THREAD

**Issue by x0b** [x0b/rcx#78]
A release of rcx to the alpha channel is planned soon™. 

> ℹ️ The next release of rcx will be delayed by approximately 3-4 weeks due to current events in my personal live.

Changes & Improvements will include:
 - various bug fixes
 - APK size improvements (>20% size reduction)
 - dependency and toolchain upgrades
 - appcenter crashlogging (replaces Firebase)
 - rclone RCD, DocumentsProvider (VCP), SAF-II
   TODO: 
     - Implement shortcut to channel settings: https://developer.android.com/training/notify-user/channels#UpdateChannel
     - #76 
 - Android 11/R support
 - Onboarding pages to better explain RCX to both old and new users
 - Translation support
 - [related issues in the milestone](https://github.com/x0b/rcx/milestone/12)

**Comment by thiscantbeserious** [comment]
@x0b is there a way to integrate auto-sync of folders that you can trigger periodically via a timer or another condition instead of just manually? or maybe via a tasker plugin integration?

**Comment by x0b** [comment]
> @x0b is there a way to integrate auto-sync of folders that you can trigger periodically via a timer or another condition instead of just manually? or maybe via a tasker plugin integration?

It is planned and partially under way, yes.

**Comment by ioogithub** [comment]
> @x0b is there a way to integrate auto-sync of folders that you can trigger periodically via a timer or another condition instead of just manually? or maybe via a tasker plugin integration?

I have been searching around trying to find a solution for this. This would be a killer feature for sure and really increase the use case. Right now I use RCX occasionally but automation would make it an essential app.

Is there currently any way to automate anything with RCX with third party tools or is it completely a manual experience?

**Comment by x0b** [comment]
Sorry, didn't get a notification.

> Is there currently any way to automate anything with RCX with third party tools or is it completely a manual experience?

Unfortunately it is completely manual.

**Comment by x0b** [comment]
Closing as `v1.12.0` has been released.
