### ISSUE TITLE
Password creation

### ISSUE THREAD

**Issue by purpleden** [x0b/rcx#81]
RCX 1.11.4

For the password creation, is it possible we are able to paste a password in, instead of using the internal creation method?

**Comment by x0b** [comment]
Could you please add screenshots and/or more details? It should be possible to use your own passwords everywhere.

**Comment by purpleden** [comment]
On my android phone (7.1.2), the password creator was displaying, and no matter what I tried, I was unable to paste/add/edit passwords within the password field, the same with my chromebook. I've just reinstalled both again from scratch on top of the existing installs, and they are now working. Strange.
