### ISSUE TITLE
Cannot See Shared Drives Directory on Google Drives

### ISSUE THREAD

**Issue by stani0502** [x0b/rcx#90]
#### What version of RCX are you using (About -> App version)?
1.11.4

#### What is your Android version, phone model and manufacturer?
Android 10

#### Which steps are required to reproduce this issue?

I already "Add Shortcut to drive" but still cannot see folder inside my drive. 
I able access the folder from rclone desktop but using rcx i cannot see the folder.

#### What are the contents of ```Android/data/io.github.x0b.rcx/files/logs/log.txt```?
<details><summary><code>log.txt</code> (click to expand) </summary><br><pre>

</pre></details>

**Comment by x0b** [comment]
Shortcuts did not make it into the release window of 1.11.4, but we are working on the next version with rclone 1.54 where this should work.

**Comment by x0b** [comment]
Version `v1.12.0` has released with rclone `1.55.1`. Please update and test again. If you still have this issue, please [open a new thread in the rclone forum](forum.rclone.org/) or a new issue in the rclone repo.
