### ISSUE TITLE
Cancel or stop a download file

### ISSUE THREAD

**Issue by lizard-Szilard** [x0b/rcx#91]
#### Pre-Submission checklist

 - [x] There is no existing issue that already asks for this feature.<br />
       _If no, please add a_ +1, _and maybe a comment if you have more to add._
 - [ ] The feature already exists in rclone (on your PC or in Termux)
 - [ ] I am prepared to help make this feature

#### What version of RCX are you using (About -> App version)?
App version: 1.11.4
Rclone version: v1.51.0

#### What problem are you trying to solve?
Cancel or stop a download

#### What should RCX be able to do differently with help this problem?
Just experience with sync to google drive by the app, the app the same as rclone on termux when I downloaded a file its size 1GB up in external memory(sd card) it's will take a minutes to stable a connection download (I meant connection speed). I hope you make a feature for cancel or stop a file download without close the app and adding the doc reference rclone, maybe it's useful for who new know about rclone.

**Comment by x0b** [comment]
The time to reach a stable connection speed largely depends on technical parameters (like network congestion, packet loss and latency) while the network tries to figure out how much data it can transmit. This really depends on the quality of your mobile data or WIFI provider and their own connection to the larger internet, and rclone cannot change this.

RCX should show you a cancel button though - could you maybe add a screenshot where the download is visible? That may help to figure out what is going wrong.

**Comment by x0b** [comment]
Closing as stale. If you experience the same issue again, please add more details.
