### ISSUE TITLE
Getting "Error creating remote"

### ISSUE THREAD

**Issue by kcthrn** [x0b/rcx#92]
#### What version of RCX are you using (About -> App version)?
1.11.4

#### What is your Android version, phone model and manufacturer?
Android 6.0.1, 1+1

#### Which steps are required to reproduce this issue?

 1. Add remote
 2. Select Box, Dropbox, Google Drive, Google Photos, HubiC, Microsoft OneDrive, pCloud, Yandex Disk
 3. Fill all fields except those with "Leave blank normally"

#### What are the contents of ```Android/data/io.github.x0b.rcx/files/logs/log.txt```?
<details><summary><code>log.txt</code> (click to expand) </summary><br><pre>

No `logs` folder within `Android/data/io.github.x0b.rcx/files/`

</pre></details>

**Comment by x0b** [comment]
You might have installed an incompatible version. Could you also please add the rclone version from **About -> Rclone version**?

**Comment by kcthrn** [comment]
Rclone version is v1.51.0

**Comment by x0b** [comment]
Could you enable rclone logging like the bug template has asked...
> Please also enable rclone logging (Settings > Logging > Log Rclone errors)

...and afterwards retry your steps? The log file should be in the directory `Android/data/io.github.x0b.rcx/files/logs` on your primary storage (internal storage).

**Comment by kcthrn** [comment]
At the time I _did_ have logging enabled, but there was no logs folder.

This time I tried the remote QingCloud QingStor with these entered:

Remote name: a
Zone: pek3a
Retries: 2

Then I got this error when tapping the entry in the remotes list: "Error retrieving directory content"

These are the logs, but this is the only remote that generated logs. I repeated creating other remotes but there were no logs generated for them.

```
2020-09-22 05:58:47 - 2020/09/22 09:58:47 DEBUG : rclone: Version "v1.51.0" starting with parameters ["/data/app/io.github.x0b.rcx-1/lib/arm/librclone.so" "--cache-chunk-path" "/data/user/0/io.github.x0b.rcx/cache" "--cache-db-path" "/data/user/0/io.github.x0b.rcx/cache" "--config" "/data/user/0/io.github.x0b.rcx/files/rclone.conf" "-vvv" "lsjson" "a:"]
2020/09/22 09:58:47 DEBUG : Using config file from "/data/user/0/io.github.x0b.rcx/files/rclone.conf"
2020/09/22 09:58:47 ERROR : : error listing: access key not provided
2020/09/22 09:58:47 Failed to lsjson with 2 errors: last error was: error in ListJSON: access key not provided

2020-09-22 05:59:40 - 2020/09/22 09:59:40 DEBUG : rclone: Version "v1.51.0" starting with parameters ["/data/app/io.github.x0b.rcx-1/lib/arm/librclone.so" "--cache-chunk-path" "/data/user/0/io.github.x0b.rcx/cache" "--cache-db-path" "/data/user/0/io.github.x0b.rcx/cache" "--config" "/data/user/0/io.github.x0b.rcx/files/rclone.conf" "-vvv" "lsjson" "a:"]
2020/09/22 09:59:40 DEBUG : Using config file from "/data/user/0/io.github.x0b.rcx/files/rclone.conf"
2020/09/22 09:59:40 ERROR : : error listing: access key not provided
2020/09/22 09:59:40 Failed to lsjson with 2 errors: last error was: error in ListJSON: access key not provided

2020-09-22 05:59:45 - 2020/09/22 09:59:45 DEBUG : rclone: Version "v1.51.0" starting with parameters ["/data/app/io.github.x0b.rcx-1/lib/arm/librclone.so" "--cache-chunk-path" "/data/user/0/io.github.x0b.rcx/cache" "--cache-db-path" "/data/user/0/io.github.x0b.rcx/cache" "--config" "/data/user/0/io.github.x0b.rcx/files/rclone.conf" "-vvv" "lsjson" "a:"]
2020/09/22 09:59:45 DEBUG : Using config file from "/data/user/0/io.github.x0b.rcx/files/rclone.conf"
2020/09/22 09:59:45 ERROR : : error listing: access key not provided
2020/09/22 09:59:45 Failed to lsjson with 2 errors: last error was: error in ListJSON: access key not provided
```

**Comment by x0b** [comment]
It seems there are multiple issues.

**Regarding "Error creating remote" :** This is really mysterious - usually, there should be a corresponding error message in the logs. Going to the "About" screen should either produce a log mesage, or it should report the rclone version as `-1`. 

Unfortunately, the logging system is currently not sophisticated enough to debug this more in-depth. I've added a feature request to the backlog (https://github.com/x0b/rcx/issues/93).

**Regarding QingStor:** Did you configure an access key id and secret secret access key? From the documentation, it seems that QingStore requires those on RCX.

**Comment by kcthrn** [comment]
> **Regarding QingStor:** Did you configure an access key id and secret secret access key? From the documentation, it seems that QingStore requires those on RCX.

No because those fields have "Leave blank for anonymous access". I've actually never heard of a cloud service called QingStor
before trying RCX.

**Comment by x0b** [comment]
> I've actually never heard of a cloud service called QingStor before trying RCX.

I don't know that much about it myself - its just one of those providers that rclone supports, which means that it is supported in RCX. There is still a bug though - the access key values are definately not optional.

**Comment by x0b** [comment]
I have most likely found the underlying issue. 

All of the remotes you have mentioned require a browser login (using OAuth). If that login process is not completed, all future authentication attemps will fail until the RCX is force-closed.

We'll fix this in an upcoming version.
