### ISSUE TITLE
RCX fails to list all the files (~30K) of a folder [Crypt and Google Drive]

### ISSUE THREAD

**Issue by 1024mb** [x0b/rcx#94]
#### What version of RCX are you using (About -> App version)?

1.11.4

#### What is your Android version, phone model and manufacturer?

Android 10.

#### Which steps are required to reproduce this issue?

1. Open crypt remote
2. Expand folder with lots of files
3. RCX doesn't load anything.

#### What are the contents of ```Android/data/io.github.x0b.rcx/files/logs/log.txt```?
<details><summary><code>log.txt</code> (click to expand) </summary><br><pre>

2020/09/24 22:22:55 DEBUG : Using config file from "/data/user/0/io.github.x0b.rcx/files/rclone.conf"
2020/09/24 22:28:01 ERROR : : error listing: couldn't list directory: Get https://www.googleapis.com/drive/v3/files?alt=json&fields=files%28id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink%29%2CnextPageToken%2CincompleteSearch&includeItemsFromAllDrives=true&pageSize=1000&pageToken=XXXXXXXX&prettyPrint=false&q=trashed%3Dfalse+and+%28%27YYYYYY%27+in+parents%29&supportsAllDrives=true: dial tcp: lookup www.googleapis.com: No address associated with hostname
2020/09/24 22:28:01 Failed to lsjson with 2 errors: last error was: error in ListJSON: couldn't list directory: Get https://www.googleapis.com/drive/v3/files?alt=json&fields=files%28id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink%29%2CnextPageToken%2CincompleteSearch&includeItemsFromAllDrives=true&pageSize=1000&pageToken=XXXXXXXX&prettyPrint=false&q=trashed%3Dfalse+and+%28%27YYYYYY%27+in+parents%29&supportsAllDrives=true: dial tcp: lookup www.googleapis.com: No address associated with hostname

</pre></details>

RCX always fails to retrieve all the files within a folder when the file amount is pretty big. In my case I've tried expanding a folder with ~30K files and it showed me an error with an empty list, and also I got that on the log (I've removed the token [XXXXXX] and a encrypted name [YYYYYY]). Any other folder with a lot fewer files does expand and lists well. The only problem happens when I'm trying to open that folder.

rclone on Windows does list all the 29354 files successfully.  
I'm using a crypt remote pointing to a Google Drive remote.

**Comment by x0b** [comment]
> dial tcp: lookup www.googleapis.com: No address associated with hostname

Strange. The log indicates a DNS resolution error, which are unfortunately quite common on google drive. However, this error should happen regardless of the number of items in a folder. 

To replicate this, we're going to need a bit of information

- Have you set any flags on the crypt or gdrive? 
- What is the version of Rclone on your Windows PC, where it works?
- How big (in terms of number of items) are the folders where it still works in RCX (approximately)

It might me be that the rclone version in 1.11.4 is just to old, and this problem is resolved when finally release the update.

**Comment by 1024mb** [comment]
> 
> 
> > dial tcp: lookup [www.googleapis.com](http://www.googleapis.com): No address associated with hostname
> 
> Strange. The log indicates a DNS resolution error, which are unfortunately quite common on google drive. However, this error should happen regardless of the number of items in a folder.
> 
> To replicate this, we're going to need a bit of information
> 
>     * Have you set any flags on the crypt or gdrive?
> 
>     * What is the version of Rclone on your Windows PC, where it works?
> 
>     * How big (in terms of number of items) are the folders where it still works in RCX (approximately)
> 
> 
> It might me be that the rclone version in 1.11.4 is just to old, and this problem is resolved when finally release the update.

1. Do you mean on my PC? Because I don't see an option on RCX. On Windows I use --fast-list.
2. I'm using the latest version, 1.53.1
3. The folders that work on RCX have from 3 to 431 files and/or folders.

I thought about that also, maybe this has been fixed on latest rclone versions. I'll have to wait for you to release a new version to discard this.

Thanks.

**Comment by x0b** [comment]
Version `v1.12.0` has released with rclone `1.55.1`. Please update and test again. If you still have this issue, please [open a new thread in the rclone forum](forum.rclone.org/) or a new issue in the rclone repo.

**Comment by x0b** [comment]
Not retested after 2 months, closing.
