### ISSUE TITLE
JottaCloud OAuth (Token)

### ISSUE THREAD

**Issue by turguenev** [x0b/rcx#96]
#### What version of RCX are you using (About -> App version)?
1.11.4

#### What is your Android version, phone model and manufacturer?
Android 10.

#### Which steps are required to reproduce this issue?
(JottaCloud support works fine with rclone in my laptop)
- Import rclone.conf (Jottacloud and crypt)
- Wait to the expiry date in rclone.conf 
- rclone should renew the token from JottaCloud
- When accessing the remote, I get "Error retrieving directory content".
- The rclone.conf file of my laptop has a different expiry date because it renews the token, but RCX does not.
- **Unlike [#68](https://github.com/x0b/rcx/issues/68), my rclone.conf has not been modified after import**

#### What are the contents of ```Android/data/io.github.x0b.rcx/files/logs/log.txt```?
<details><summary><code>log.txt</code> (click to expand) </summary><br><pre>

2020-10-02 09:06:50 - 2020/10/02 07:06:37 DEBUG : rclone: Version "v1.51.0" starting with parameters ["/data/app/io.github.x0b.rcx-vTV1EnD-2yxULV19GxBM7A==/lib/arm64/librclone.so" "--cache-chunk-path" "/data/user/0/io.github.x0b.rcx/cache" "--cache-db-path" "/data/user/0/io.github.x0b.rcx/cache" "--config" "/data/user/0/io.github.x0b.rcx/files/rclone.conf" "-vvv" "lsjson" "secret:"]
2020/10/02 07:06:37 DEBUG : Using config file from "/data/user/0/io.github.x0b.rcx/files/rclone.conf"
2020/10/02 07:06:37 DEBUG : jottacloud: Loaded invalid token from config file - ignoring
2020/10/02 07:06:38 DEBUG : jottacloud: Token refresh failed try 1/5: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Stale token"}
2020/10/02 07:06:39 DEBUG : jottacloud: Loaded invalid token from config file - ignoring
2020/10/02 07:06:39 DEBUG : jottacloud: Token refresh failed try 2/5: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Stale token"}
2020/10/02 07:06:40 DEBUG : jottacloud: Loaded invalid token from config file - ignoring
2020/10/02 07:06:40 DEBUG : jottacloud: Token refresh failed try 3/5: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Stale token"}
2020/10/02 07:06:41 DEBUG : jottacloud: Loaded invalid token from config file - ignoring
2020/10/02 07:06:41 DEBUG : jottacloud: Token refresh failed try 4/5: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Stale token"}
2020/10/02 07:06:42 DEBUG : jottacloud: Loaded invalid token from config file - ignoring
2020/10/02 07:06:43 DEBUG : jottacloud: Token refresh failed try 5/5: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Stale token"}
2020/10/02 07:06:44 DEBUG : jottacloud root 'Luigi': Token expired but no uploads in progress - doing nothing
2020/10/02 07:06:44 DEBUG : jottacloud: Loaded invalid token from config file - ignoring
2020/10/02 07:06:44 DEBUG : jottacloud: Token refresh failed try 1/5: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Stale token"}
2020/10/02 07:06:45 DEBUG : jottacloud: Loaded invalid token from config file - ignoring
2020/10/02 07:06:45 DEBUG : jottacloud: Token refresh failed try 2/5: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Stale token"}
2020/10/02 07:06:46 DEBUG : jottacloud: Loaded invalid token from config file - ignoring
2020/10/02 07:06:46 DEBUG : jottacloud: Token refresh failed try 3/5: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Stale token"}
2020/10/02 07:06:47 DEBUG : jottacloud: Loaded invalid token from config file - ignoring
2020/10/02 07:06:48 DEBUG : jottacloud: Token refresh failed try 4/5: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Stale token"}
2020/10/02 07:06:49 DEBUG : jottacloud: Loaded invalid token from config file - ignoring
2020/10/02 07:06:49 DEBUG : jottacloud: Token refresh failed try 5/5: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Stale token"}
2020/10/02 07:06:50 Failed to create file system for "secret:": failed to make remote jottacloud:"Luigi" to wrap: couldn't get customer info: Get https://api.jottacloud.com/account/v1/customer: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Stale token"}

2020-10-02 09:07:02 - 2020/10/02 07:06:56 DEBUG : rclone: Version "v1.51.0" starting with parameters ["/data/app/io.github.x0b.rcx-vTV1EnD-2yxULV19GxBM7A==/lib/arm64/librclone.so" "--cache-chunk-path" "/data/user/0/io.github.x0b.rcx/cache" "--cache-db-path" "/data/user/0/io.github.x0b.rcx/cache" "--config" "/data/user/0/io.github.x0b.rcx/files/rclone.conf" "-vvv" "lsjson" "jottacloud:"]
2020/10/02 07:06:56 DEBUG : Using config file from "/data/user/0/io.github.x0b.rcx/files/rclone.conf"
2020/10/02 07:06:56 DEBUG : jottacloud: Loaded invalid token from config file - ignoring
2020/10/02 07:06:56 DEBUG : jottacloud: Token refresh failed try 1/5: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Stale token"}
2020/10/02 07:06:57 DEBUG : jottacloud: Loaded invalid token from config file - ignoring
2020/10/02 07:06:58 DEBUG : jottacloud: Token refresh failed try 2/5: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Stale token"}
2020/10/02 07:06:59 DEBUG : jottacloud: Loaded invalid token from config file - ignoring
2020/10/02 07:06:59 DEBUG : jottacloud: Token refresh failed try 3/5: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Stale token"}
2020/10/02 07:07:00 DEBUG : jottacloud: Loaded invalid token from config file - ignoring
2020/10/02 07:07:00 DEBUG : jottacloud: Token refresh failed try 4/5: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Stale token"}
2020/10/02 07:07:01 DEBUG : jottacloud: Loaded invalid token from config file - ignoring
2020/10/02 07:07:01 DEBUG : jottacloud: Token refresh failed try 5/5: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Stale token"}
2020/10/02 07:07:02 Failed to create file system for "jottacloud:": couldn't get customer info: Get https://api.jottacloud.com/account/v1/customer: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Stale token"}
</pre></details>

#### What are the contents of ```rclone.conf``` imported?
<details><summary><code>rclone.conf</code> (click to expand) </summary><br><pre>

[jottacloud]
type = jottacloud
tokenURL = https://id.jottacloud.com/auth/realms/jottacloud/protocol/openid-connect/token
token = {"access_token":"...y......h","token_type":"bearer","refresh_token":"...y.......h","expiry":"2020-10-01T19:56:49.537980418+02:00"}
device = Jotta
mountpoint = Archive
configVersion = 1

[secret]
type = crypt
remote = jottacloud:Folder
filename_encryption = standard
directory_name_encryption = true
password = FakePassword
password2 = FakePassword2
</pre></details>

#### What are the contents of ```rclone.conf``` from my laptop?
<details><summary><code>rclone.conf</code> (click to expand) </summary><br><pre>

[jottacloud]
type = jottacloud
tokenURL = https://id.jottacloud.com/auth/realms/jottacloud/protocol/openid-connect/token
token = {"access_token":"...y........w","token_type":"bearer","refresh_token":"...y.......w","expiry":"2020-10-02T09:28:02.937435667+02:00"}
device = Jotta
mountpoint = Archive
configVersion = 1

[secret]
type = crypt
remote = jottacloud:Folder
filename_encryption = standard
directory_name_encryption = true
password = FakePassword
password2 = FakePassword2

</pre></details>

Import rclone.conf (Jottacloud and crypt). Wait to the expiry date in rclone.conf. RCX (rclone) should renew the token from JottaCloud. When accessing the remote, I get "Error retrieving directory content". The rclone.conf file of my laptop has a different expiry date because it renews the token, but RCX does not. **Unlike [#68](https://github.com/x0b/rcx/issues/68), my rclone.conf has not been modified after import**. 

- **Probably the problem comes from the fact that RCX uses rclone version 1.51, and the current version of rclone (and the one I use in my laptop) is 1.53.1?**

Thanks.

</pre></details>

**Comment by x0b** [comment]
This is defnitely an issue in rclone, but I'm not sure if it has alread been fixed between 1.51.0 => 1.53.1. It could be related to https://github.com/rclone/rclone/issues/4645.

The next version of RCX (1.12) will include rclone 1.54. My idea would be to re-test with that, and then figure this out on the rclone side if it still doesn't work.

**Comment by x0b** [comment]
Version `v1.12.0` has released with rclone `1.55.1`. Please update and test again. If you still have this issue, please [open a new thread in the rclone forum](forum.rclone.org/) or a new issue in the rclone repo.

**Comment by halictuz** [comment]
> 
> 
> Version `v1.12.0` has released with rclone `1.55.1`. Please update and test again. If you still have this issue, please [open a new thread in the rclone forum](forum.rclone.org/) or a new issue in the rclone repo.

This is still an issue. Using latest version on Windows PC of rclone and latest version of RCX on Android 12. Same error: "Error retrieving directory content". For jottacloud with and without rclone crypt.
